"""Alembic environment, wired for the async engine.

Two things here are not the stock template:

  1. The URL comes from core.config.settings, not from alembic.ini — the
     connection string is a secret and belongs in .env with everything else.
  2. infrastructure.database.models is imported for its side effects. Alembic
     compares the database against Base.metadata, and a model class only
     registers itself there when its module is imported. Miss that import and
     autogenerate cheerfully emits a migration that DROPs every table it cannot
     see.
"""
from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from core.config import settings
from infrastructure.database.base import Base

# noqa: F401 — imported for the side effect of registering every mapper.
import infrastructure.database.models  # noqa: F401

config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _include_object(obj, name, type_, reflected, compare_to):
    """Keep autogenerate away from things it does not own.

    pg_trgm creates its own indexes and Postgres owns the extension catalogs;
    neither appears in Base.metadata, so without this filter every autogenerated
    revision would try to drop them.
    """
    if type_ == "table" and name in {"spatial_ref_sys"}:
        return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting — `alembic upgrade head --sql`."""
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        include_object=_include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Both default to False, which means a changed column type or a changed
        # server_default silently produces an empty migration.
        compare_type=True,
        compare_server_default=True,
        include_object=_include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
