"""Initial schema.

Hand-written rather than autogenerated. `alembic revision --autogenerate` cannot
see four things the models depend on, and would emit a migration that fails on a
clean database:

  * The pgcrypto / pg_trgm extensions. gen_random_uuid() is the server default on
    every primary key, and idx_users_username_trgm needs gin_trgm_ops — CREATE
    INDEX fails outright without the extension.
  * messages.search_vector is a GENERATED ... STORED column. Autogenerate
    reflects it as an ordinary TSVECTOR and drops the generation expression, so
    the column would exist but stay permanently NULL and full-text search would
    silently match nothing.
  * The partial unique indexes (idx_conversations_single_public,
    idx_friend_requests_pending_pair). The WHERE clause is what makes them
    partial; without it "one public conversation" becomes "one conversation".
  * The set_updated_at() trigger. base.py's TimestampMixin declares
    server_onupdate=FetchedValue(), which tells SQLAlchemy "the database
    maintains this" — but nothing in the repo ever created the trigger that was
    supposed to. updated_at would be frozen at insert time.

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-08-05
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- extensions -------------------------------------------------------
    # pgcrypto: gen_random_uuid(). Built into PG13+, but creating it is a no-op
    # there and keeps this migration working on older servers.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # pg_trgm: the trigram operator class behind user search.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # --- updated_at trigger ----------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )

    # --- users ------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="offline", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('online', 'offline', 'away')", name="chk_users_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("email"),
    )
    op.execute(
        "CREATE INDEX idx_users_username_trgm ON users USING gin (username gin_trgm_ops)"
    )

    # --- conversations ----------------------------------------------------
    op.create_table(
        "conversations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("type IN ('public', 'private', 'group')", name="chk_conversations_type"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Partial unique index: at most one row with type='public' may exist, but
    # 'private' and 'group' stay unconstrained. This is what makes the global
    # room a database invariant rather than a hope.
    op.execute(
        "CREATE UNIQUE INDEX idx_conversations_single_public "
        "ON conversations (type) WHERE type = 'public'"
    )

    # --- messages ---------------------------------------------------------
    # Before conversation_members: that table carries an FK to messages.id.
    op.create_table(
        "messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sender_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_edited", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(content, ''))", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # DESC matches the history query's ORDER BY created_at DESC, so the index
    # satisfies the sort as well as the filter.
    op.execute(
        "CREATE INDEX idx_messages_conversation_created "
        "ON messages (conversation_id, created_at DESC)"
    )
    op.create_index("idx_messages_sender", "messages", ["sender_id"])
    op.execute(
        "CREATE INDEX idx_messages_search_vector ON messages USING gin (search_vector)"
    )

    # --- conversation_members --------------------------------------------
    op.create_table(
        "conversation_members",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.Text(), server_default="member", nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("muted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_read_message_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name="chk_members_role"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_read_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "user_id", name="uq_conversation_member"),
    )
    op.create_index("idx_conversation_members_user", "conversation_members", ["user_id"])
    op.create_index(
        "idx_conversation_members_conversation", "conversation_members", ["conversation_id"]
    )

    # --- refresh_tokens ---------------------------------------------------
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("idx_refresh_tokens_user_id", "refresh_tokens", ["user_id"])

    # --- notifications ----------------------------------------------------
    op.create_table(
        "notifications",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "type IN ('new_message', 'friend_request', 'system_announcement', 'background_task')",
            name="chk_notifications_type",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Partial: the unread badge only ever queries is_read = false, so indexing
    # the read rows would be dead weight that grows forever.
    op.execute(
        "CREATE INDEX idx_notifications_user_unread "
        "ON notifications (user_id, is_read) WHERE is_read = false"
    )

    # --- friend_requests --------------------------------------------------
    op.create_table(
        "friend_requests",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("sender_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("recipient_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("sender_id <> recipient_id", name="chk_no_self_request"),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'declined')", name="chk_friend_requests_status"
        ),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Partial: only one *pending* request per direction. Declined ones may
    # legitimately repeat, so a full unique index would block ever asking again.
    op.execute(
        "CREATE UNIQUE INDEX idx_friend_requests_pending_pair "
        "ON friend_requests (sender_id, recipient_id) WHERE status = 'pending'"
    )
    op.create_index("idx_friend_requests_recipient", "friend_requests", ["recipient_id", "status"])

    # --- friendships ------------------------------------------------------
    op.create_table(
        "friendships",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id_a", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id_b", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        # Forces a canonical ordering, so a friendship cannot be stored twice
        # as (a,b) and (b,a) — the unique constraint below then actually means
        # "one friendship per pair".
        sa.CheckConstraint("user_id_a < user_id_b", name="chk_friendship_order"),
        sa.ForeignKeyConstraint(["user_id_a"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id_b"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id_a", "user_id_b", name="uq_friendship_pair"),
    )
    op.create_index("idx_friendships_a", "friendships", ["user_id_a"])
    op.create_index("idx_friendships_b", "friendships", ["user_id_b"])

    # --- system_announcements --------------------------------------------
    op.create_table(
        "system_announcements",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # The SSE stream polls this by created_at on every tick.
    op.create_index("idx_system_announcements_created", "system_announcements", ["created_at"])

    # --- background_tasks -------------------------------------------------
    op.create_table(
        "background_tasks",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("task_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("progress", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name="chk_background_tasks_status",
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="chk_background_tasks_progress"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_background_tasks_user", "background_tasks", ["user_id", "status"])

    # --- user_sessions ----------------------------------------------------
    op.create_table(
        "user_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_info", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_sessions_user", "user_sessions", ["user_id"])

    # --- attach the updated_at trigger ------------------------------------
    # Only the three tables carrying TimestampMixin.
    for table in ("users", "conversations", "background_tasks"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
            """
        )


def downgrade() -> None:
    for table in ("users", "conversations", "background_tasks"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # Reverse creation order: children before parents.
    op.drop_table("user_sessions")
    op.drop_table("background_tasks")
    op.drop_table("system_announcements")
    op.drop_table("friendships")
    op.drop_table("friend_requests")
    op.drop_table("notifications")
    op.drop_table("refresh_tokens")
    op.drop_table("conversation_members")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("users")

    # Extensions are left in place on purpose: they are database-wide and may
    # well be in use by something outside this application's schema.
